CREATE TABLE source  (
  `col_bit` BOOLEAN,
  `col_id`  int,
  `col_bool` BOOLEAN,
  `col_boolean` BOOLEAN,
  `col_smallint` smallint,
  `col_mediumint` INTEGER,
  `col_int` int,
  `col_bigint` bigint,
  `col_integer` integer,
  `col_float`   float,
  `col_double`   double,
  `col_decimal` decimal,
  `col_date` date,
  `col_datetime` timestamp,
  `col_time` time,
  `col_timestamp` timestamp,
--   `col_year` date,
  `col_char` char,
  `col_varchar` varchar,
  `col_text` string,
  `col_tinytext` string,
  `col_mediumtext` string,
  `col_longtext` string,
  `col_binary`  BYTES,
  `col_varbinary` BYTES,
  `col_tinyblob` BYTES,
  `col_blob` BYTES,
  `col_mediumblob` BYTES,
  `col_longblob` BYTES,
  `col_enum` string,
  `col_set`  string,
  `col_json` string
)with(
	    'connector' = 'mysql-x',
      'url' = 'jdbc:mysql://127.0.0.1:3306/dev',
      'table-name' = 'test',
      'username' = 'username',
      'password' = 'password',
      'scan.increment.column' = 'col_int',
      'scan.polling-interval' = '3000',
      'scan.start-location' = '1',
      'scan.fetch-size' = '2',
      'scan.query-timeout' = '10'
);

CREATE TABLE sink  (
  `col_bit` BOOLEAN,
  `col_id`  int,
  `col_bool` BOOLEAN,
  `col_boolean` BOOLEAN,
  `col_smallint` smallint,
  `col_mediumint` INTEGER,
  `col_int` int,
  `col_bigint` bigint,
  `col_integer` integer,
  `col_float`   float,
  `col_double`   double,
  `col_decimal` decimal,
  `col_date` date,
  `col_datetime` timestamp,
  `col_time` time,
  `col_timestamp` timestamp,
--   `col_year` date,
  `col_char` char,
  `col_varchar` varchar,
  `col_text` string,
  `col_tinytext` string,
  `col_mediumtext` string,
  `col_longtext` string,
  `col_binary`  BYTES,
  `col_varbinary` BYTES,
  `col_tinyblob` BYTES,
  `col_blob` BYTES,
  `col_mediumblob` BYTES,
  `col_longblob` BYTES,
  `col_enum` string,
  `col_set`  string,
  `col_json` string
)with(
      'connector' = 'tidb-x',
      'url' = 'jdbc:mysql://127.0.0.1:4000/db_dev',
      'table-name' = 'sink',
      'username' = 'username',
      'password' = 'password'
);

insert into sink
select *
from source;
