FROM rohitbasu77/oracle11g:latest

#hostname: localhost or docker machine ip
#port: 1521
#sid: xe
#username: system
#password: oracle
#Password for SYS & SYSTEM is oracle
#Password for fareuser, searchuser, bookinguser, checkinuser is rohit123

LABEL maintainer="www.dtstack.com"


EXPOSE 1521
EXPOSE 22

